import { useEffect, useState } from "react";
import { ArrowDownLeft, ArrowUpRight, AudioWaveform, ChevronRight, Disc3, Drum, Menu, Music2, SlidersHorizontal, Sparkles, X, Instagram } from "lucide-react";
import { Link } from "wouter";
import SiteLogo from "@/components/SiteLogo";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import { useLanguage, type Language } from "@/contexts/LanguageContext";

const factoryBanner = `${import.meta.env.BASE_URL}assets/factory-pack-banner-a.jpg`;

const images = {
  pad: `${import.meta.env.BASE_URL}assets/pad.jpg`,
  drum: `${import.meta.env.BASE_URL}assets/drum.jpg`,
  loop: `${import.meta.env.BASE_URL}assets/loop.jpg`,
};

const ui = {
  he: {
    features: "יכולות", architecture: "איך זה עובד", privacy: "פרטיות", vision: "החזון", dive: "לצלול פנימה", close: "סגירת תפריט", open: "פתיחת תפריט", discover: "לגלות את הסטודיו", engine: "להכיר את המנוע", productKicker: "תחנת עבודה מוזיקלית לאנדרואיד", productLead: "לא רק סינתיסייזר.", productAccent: "סטודיו שלם.", productBody: "L Studio נבנתה כדי לתת לכל אחד מקום ליצור, גם בלי מחשב, בלי רקע מוזיקלי ובלי תוכנה יקרה. כל מה שצריך להלחין, לנגן ולהקליט נמצא במקום אחד.", four: "ארבעה כלים.", oneFlow: "זרימה אחת.", featureIntro: "סאונד, לופר, תופים, פאד ומיקרופון, מחוברים לנתיב אודיו אחד, בתוך חוויה ישירה שאפשר ללמוד תוך כדי משחק.", explore: "TAP TO EXPLORE", interfaceKicker: "THE INTERFACE IS THE INSTRUMENT", interfaceTitle: "כל מחווה הופכת לרגע.", interfaceText: "הממשק של L Studio נבנה למסך קטן אבל עם שאיפה גדולה: לתת לך לראות, לשמוע ולהרגיש את היצירה בזמן אמת.", under: "הממשק מנגן.", holds: "המנוע מחזיק.", underText: "מתחת לכל מחווה יש נתיב אודיו מלא: מהקלידים, דרך הקול והאפקטים, ועד למיקס הסטריאו והקלטת ה־WAV. בלי עטיפות. בלי קיצורי דרך.", visionKicker: "A STUDIO FOR EVERYONE", visionTitle: "כלי איכותי לא צריך להיות רחוק.", visionBody: "החזון של L Studio הוא לבנות סביב האפליקציה קהילה של אמנים ומוזיקאים, בעיקר עבור אנשים שלא תמיד הייתה להם גישה למחשב, לתוכנה מקצועית או למרחב יצירה משלהם.", visionBody2: "אנחנו מאמינים שיצירתיות לא אמורה להיות תלויה בציוד יקר או בידע מוקדם. היא צריכה להתחיל בלחיצה אחת, להמשיך בסקרנות, ולהפוך לקול שהוא שלך.", access: "גישה ליצירה", accessText: "תחנת עבודה שלמה בכיס, עם שפה פשוטה, שליטה עמוקה ואודיו מקומי.", community: "קהילה בתנועה", communityText: "מקום לאמנים לשתף רעיונות, לופים, סולמות ותהליכי יצירה.", future: "השלב הבא", futureText: "להפוך כלי נגיש לתשתית שמאפשרת ליוצרים לבנות עתיד משלהם.", next: "הכלי הבא שלך", waits: "כבר מחכה.", ctaText: "L Studio נבנה עבור מי שלא מסתפק בצליל אחד, בסולם אחד, או בדרך אחת ליצור.", audio: "100% LOCAL AUDIO",
  },
  en: {
    features: "Features", architecture: "How it works", privacy: "Privacy", vision: "Vision", dive: "Explore the studio", close: "Close menu", open: "Open menu", discover: "Discover the studio", engine: "Meet the engine", productKicker: "A music workstation for Android", productLead: "Not just a synthesizer.", productAccent: "A complete studio.", productBody: "L Studio gives anyone a place to create, without a computer, a music degree or expensive software. Everything you need to compose, play and record lives in one place.", four: "Four instruments.", oneFlow: "One flow.", featureIntro: "Sound, looper, drums, pad and microphone, connected to one audio path inside an experience you can learn by playing.", explore: "TAP TO EXPLORE", interfaceKicker: "THE INTERFACE IS THE INSTRUMENT", interfaceTitle: "Every gesture becomes a moment.", interfaceText: "L Studio is designed for a small screen with a bigger ambition: to let you see, hear and feel the work in real time.", under: "The interface plays.", holds: "The engine holds.", underText: "Under every gesture is a complete audio path: from keys, through voices and effects, to the stereo mix and WAV capture. No wrappers. No shortcuts.", visionKicker: "A STUDIO FOR EVERYONE", visionTitle: "Quality tools should not feel out of reach.", visionBody: "L Studio is building toward a community of artists and musicians, especially people who have not always had access to a computer, professional software or a creative space of their own.", visionBody2: "Creativity should not depend on expensive gear or prior knowledge. It should begin with one tap, continue through curiosity, and become a voice that is yours.", access: "Access to creation", accessText: "A complete workstation in your pocket, with simple language, deep control and local audio.", community: "A community in motion", communityText: "A place for artists to share ideas, loops, scales and creative processes.", future: "The next step", futureText: "Turn an accessible tool into infrastructure that helps creators build their own future.", next: "Your next instrument", waits: "is already waiting.", ctaText: "L Studio is for anyone who is not satisfied with one sound, one scale, or one way to create.", audio: "100% LOCAL AUDIO",
  },
  ru: {
    features: "Возможности", architecture: "Как это работает", privacy: "Приватность", vision: "Видение", dive: "Открыть студию", close: "Закрыть меню", open: "Открыть меню", discover: "Открыть студию", engine: "Познакомиться с движком", productKicker: "Музыкальная рабочая станция для Android", productLead: "Не просто синтезатор.", productAccent: "Целая студия.", productBody: "L Studio даёт каждому место для творчества, без компьютера, музыкального образования и дорогих программ. Всё для сочинения, игры и записи собрано в одном месте.", four: "Четыре инструмента.", oneFlow: "Один поток.", featureIntro: "Звук, лупер, ударные, пад и микрофон, соединены одним аудиопутём в опыте, которому можно учиться через игру.", explore: "TAP TO EXPLORE", interfaceKicker: "THE INTERFACE IS THE INSTRUMENT", interfaceTitle: "Каждый жест становится моментом.", interfaceText: "L Studio создана для маленького экрана с большой целью: дать увидеть, услышать и почувствовать музыку в реальном времени.", under: "Интерфейс играет.", holds: "Движок держит.", underText: "За каждым жестом стоит полный аудиопуть: от клавиш через голоса и эффекты к стереомиксу и записи WAV. Без обёрток. Без компромиссов.", visionKicker: "A STUDIO FOR EVERYONE", visionTitle: "Качественный инструмент не должен быть недоступным.", visionBody: "L Studio строит сообщество артистов и музыкантов, особенно для тех, у кого не всегда был компьютер, профессиональный софт или своё творческое пространство.", visionBody2: "Творчество не должно зависеть от дорогого оборудования или опыта. Оно начинается с одного касания, продолжается любопытством и становится вашим голосом.", access: "Доступ к творчеству", accessText: "Полная рабочая станция в кармане, с простым языком, глубоким контролем и локальным аудио.", community: "Живое сообщество", communityText: "Место для обмена идеями, лупами, гаммами и творческими процессами.", future: "Следующий шаг", futureText: "Превратить доступный инструмент в основу для будущего создателей.", next: "Ваш следующий инструмент", waits: "уже ждёт.", ctaText: "L Studio создана для тех, кому мало одного звука, одной гаммы или одного способа творить.", audio: "100% LOCAL AUDIO",
  },
  ar: {
    features: "المزايا", architecture: "كيف يعمل", privacy: "الخصوصية", vision: "الرؤية", dive: "استكشف الاستوديو", close: "إغلاق القائمة", open: "فتح القائمة", discover: "اكتشف الاستوديو", engine: "تعرّف على المحرك", productKicker: "محطة عمل موسيقية لنظام Android", productLead: "ليست مجرد مُركِّب.", productAccent: "استوديو كامل.", productBody: "تمنح L Studio الجميع مساحة للإبداع, من دون كمبيوتر أو شهادة موسيقية أو برامج باهظة. كل ما تحتاجه للتأليف والعزف والتسجيل في مكان واحد.", four: "أربع أدوات.", oneFlow: "مسار واحد.", featureIntro: "الصوت والمسجل والإيقاعات والـPad والميكروفون, متصلة بمسار صوتي واحد داخل تجربة تتعلمها باللعب.", explore: "TAP TO EXPLORE", interfaceKicker: "THE INTERFACE IS THE INSTRUMENT", interfaceTitle: "كل حركة تصبح لحظة.", interfaceText: "صُممت L Studio لشاشة صغيرة بطموح أكبر: أن ترى وتسمع وتشعر بعملك في الوقت الفعلي.", under: "الواجهة تعزف.", holds: "والمحرك يحافظ.", underText: "خلف كل حركة مسار صوتي كامل: من المفاتيح، عبر الأصوات والمؤثرات، إلى مزيج الستيريو وتسجيل WAV. بلا اختصارات.", visionKicker: "A STUDIO FOR EVERYONE", visionTitle: "الأدوات عالية الجودة يجب ألا تكون بعيدة.", visionBody: "رؤية L Studio هي بناء مجتمع من الفنانين والموسيقيين, خصوصاً لمن لم تتوفر لهم دائماً إمكانية الوصول إلى كمبيوتر أو برنامج احترافي أو مساحة إبداعية خاصة.", visionBody2: "الإبداع لا يجب أن يعتمد على معدات باهظة أو معرفة مسبقة. يجب أن يبدأ بلمسة، ويستمر بالفضول، ويصبح صوتاً يخصك.", access: "الوصول إلى الإبداع", accessText: "محطة عمل كاملة في جيبك، بلغة بسيطة وتحكم عميق وصوت محلي.", community: "مجتمع متحرك", communityText: "مكان للفنانين لمشاركة الأفكار والـLoops والسلالم ومسارات الإبداع.", future: "الخطوة التالية", futureText: "تحويل أداة متاحة إلى أساس يساعد المبدعين على بناء مستقبلهم.", next: "أداتك الموسيقية التالية", waits: "تنتظرك.", ctaText: "صُممت L Studio لمن لا يكتفي بصوت واحد أو سلم واحد أو طريقة واحدة للإبداع.", audio: "100% LOCAL AUDIO",
  },
} satisfies Record<Language, Record<string, string>>;

const testerCopy = {
  he: { kicker: "גישה מוקדמת / 44 מקומות בלבד", title: "רוצה להיות חלק מהגרסה הראשונה?", body: "השאירו פרטים וקבלו גישה מוקדמת בחינם ל-L Studio. מחפשים יוצרים, מוזיקאים ואנשים סקרנים שיעזרו לנו לדייק את הכלי.", name: "שם מלא", email: "כתובת מייל", submit: "להצטרף לרשימת הטסטרים", note: "ללא תשלום · מספר המקומות מוגבל ל-44", thanks: "הפרטים נשלחו. ניצור קשר בקרוב." },
  en: { kicker: "EARLY ACCESS / 44 SPOTS ONLY", title: "Want to be part of the first release?", body: "Leave your details for free early access to L Studio. We are looking for creators, musicians and curious people who can help us shape the tool.", name: "Full name", email: "Email address", submit: "Join the tester list", note: "Free access · Limited to 44 testers", thanks: "Details sent. We will be in touch soon." },
  ru: { kicker: "РАННИЙ ДОСТУП / ТОЛЬКО 44 МЕСТА", title: "Хочешь быть частью первого релиза?", body: "Оставь данные и получи бесплатный ранний доступ к L Studio. Мы ищем создателей, музыкантов и любопытных людей, которые помогут улучшить инструмент.", name: "Полное имя", email: "Email", submit: "В список тестеров", note: "Бесплатный доступ · Только 44 тестера", thanks: "Данные отправлены. Мы скоро свяжемся." },
  ar: { kicker: "وصول مبكر / 44 مكاناً فقط", title: "هل تريد أن تكون جزءاً من الإصدار الأول؟", body: "اترك بياناتك للحصول على وصول مبكر مجاني إلى L Studio. نبحث عن مبدعين وموسيقيين وأشخاص فضوليين يساعدوننا على تطوير الأداة.", name: "الاسم الكامل", email: "البريد الإلكتروني", submit: "الانضمام إلى قائمة المختبرين", note: "وصول مجاني · العدد محدود بـ44 مختبراً", thanks: "تم إرسال البيانات. سنتواصل معك قريباً." },
} satisfies Record<Language, Record<string, string>>;

const featureData = {
  he: [{ id: "pad", label: "PAD", title: "הופעה חיה בכף היד", description: "פאד ביצוע שמחבר קלידים, אוקטבות, ויברטו ואופי אנלוגי לשליטה ישירה במסך קטן.", icon: SlidersHorizontal, meta: "LIVE PERFORMANCE PAD", image: images.pad }, { id: "loop", label: "LOOP", title: "לוכד את הרגע", description: "לופר PCM רב־ערוצי עם הקלטה, Play, Stop, Load, Save ו־Export, כדי לבנות שכבות בלי לאבד את הרעיון.", icon: Disc3, meta: "MULTI-TRACK / WAV EXPORT", image: images.loop }, { id: "drum", label: "DRUM", title: "הקצב בידיים שלך", description: "מכונת תופים עם ערכות, BPM, Swing, עוצמה, פאנינג, צעדים אקטיביים ו־Random, קצב שאפשר לראות ולשנות.", icon: Drum, meta: "STEP SEQUENCER / BPM", image: images.drum }],
  en: [{ id: "pad", label: "PAD", title: "Live performance in your hand", description: "A performance pad that brings keys, octave, vibrato and analog character into direct control on a small screen.", icon: SlidersHorizontal, meta: "LIVE PERFORMANCE PAD", image: images.pad }, { id: "loop", label: "LOOP", title: "Capture the moment", description: "A multi-track PCM looper with Record, Play, Stop, Load, Save and Export, build layers without losing the idea.", icon: Disc3, meta: "MULTI-TRACK / WAV EXPORT", image: images.loop }, { id: "drum", label: "DRUM", title: "Your rhythm, your hands", description: "A drum machine with kits, BPM, Swing, volume, panning, active steps and Random, rhythm you can see and reshape.", icon: Drum, meta: "STEP SEQUENCER / BPM", image: images.drum }],
  ru: [{ id: "pad", label: "PAD", title: "Живое исполнение в руке", description: "Пад для исполнения, который объединяет клавиши, октаву, вибрато и аналоговый характер на маленьком экране.", icon: SlidersHorizontal, meta: "LIVE PERFORMANCE PAD", image: images.pad }, { id: "loop", label: "LOOP", title: "Поймай момент", description: "Многодорожечный PCM-лупер с Record, Play, Stop, Load, Save и Export, создавай слои, не теряя идею.", icon: Disc3, meta: "MULTI-TRACK / WAV EXPORT", image: images.loop }, { id: "drum", label: "DRUM", title: "Ритм в твоих руках", description: "Драм-машина с наборами, BPM, Swing, громкостью, панорамой, шагами и Random, ритм, который можно менять.", icon: Drum, meta: "STEP SEQUENCER / BPM", image: images.drum }],
  ar: [{ id: "pad", label: "PAD", title: "أداء حي في يدك", description: "لوحة أداء تجمع المفاتيح والأوكتاف والفيبراتو والطابع التناظري في تحكم مباشر على شاشة صغيرة.", icon: SlidersHorizontal, meta: "LIVE PERFORMANCE PAD", image: images.pad }, { id: "loop", label: "LOOP", title: "التقط اللحظة", description: "مسجل PCM متعدد المسارات مع Record وPlay وStop وLoad وSave وExport لبناء الطبقات دون فقدان الفكرة.", icon: Disc3, meta: "MULTI-TRACK / WAV EXPORT", image: images.loop }, { id: "drum", label: "DRUM", title: "الإيقاع بين يديك", description: "آلة إيقاع مع مجموعات وBPM وSwing والتحكم بالصوت والتوزيع والخطوات وRandom.", icon: Drum, meta: "STEP SEQUENCER / BPM", image: images.drum }],
} satisfies Record<Language, Array<{ id: string; label: string; title: string; description: string; icon: typeof SlidersHorizontal; meta: string; image: string }>>;

export default function Home() {
  const { language } = useLanguage();
  const [editableContent, setEditableContent] = useState<any>(null);
  useEffect(() => { fetch(`${import.meta.env.BASE_URL}content.json`).then((response) => response.ok ? response.json() : null).then(setEditableContent).catch(() => undefined); }, []);
  const text = { ...ui[language], ...(editableContent?.languages?.[language] ?? {}) };
  const tester = editableContent?.languages?.[language]?.tester ?? testerCopy[language];
  const factory = editableContent?.languages?.[language]?.factoryPack ?? { kicker: "L STUDIO PREMIUM / FACTORY PACK", title: "L Studio", accent: "Factory Pack", lede: "Eight Pages. Sixty-Four Voices.", description: "A complete sound library for L Studio.", genres: "Built for trance, techno, rap, trap, and metal.", cta: "Get early access" };
  const features = featureData[language];
  const [mobileOpen, setMobileOpen] = useState(false);
  const [activeFeature, setActiveFeature] = useState("pad");
  const selectedFeature = features.find((feature) => feature.id === activeFeature) ?? features[0];
  const SelectedIcon = selectedFeature.icon;

  return <div className="site-shell"><div className="noise" aria-hidden="true" />
    <header className={`site-header${mobileOpen ? " site-header--open" : ""}`}><div className="container header-inner"><SiteLogo /><nav className="desktop-nav" aria-label={text.features}><a href="#features">{text.features}</a><a href="#architecture">{text.architecture}</a><a href="#vision">{text.vision}</a><Link href="/privacy">{text.privacy}</Link></nav><div className="header-actions"><LanguageSwitcher /><a className="button button--small button--light" href="#early-access"><span>{text.dive}</span><ArrowUpRight size={15} /></a><button className="menu-toggle" type="button" aria-label={mobileOpen ? text.close : text.open} onClick={() => setMobileOpen((value) => !value)}>{mobileOpen ? <X size={20} /> : <Menu size={20} />}</button></div></div>{mobileOpen && <nav className="mobile-nav" aria-label={text.features}><LanguageSwitcher /><a href="#features" onClick={() => setMobileOpen(false)}>{text.features}</a><a href="#architecture" onClick={() => setMobileOpen(false)}>{text.architecture}</a><a href="#vision" onClick={() => setMobileOpen(false)}>{text.vision}</a><Link href="/privacy" onClick={() => setMobileOpen(false)}>{text.privacy}</Link></nav>}</header>
    <main>
      <section className="factory-pack-section container" id="factory-pack" dir={language === "he" || language === "ar" ? "rtl" : "ltr"}><div className="factory-pack-art" style={{ backgroundImage: `url(${factoryBanner})` }} aria-hidden="true" /><div className="factory-pack-content"><span className="kicker">{factory.kicker}</span><h2>{factory.title}<br /><em>{factory.accent}</em></h2><p className="factory-pack-lede">{factory.lede}</p><p>{factory.description}</p><div className="factory-scales"><span>222</span><span>299</span><span>333</span><span>355</span><span>396</span><span>444</span><span>463</span><span>477 Hz</span></div><p>{factory.genres}</p><a className="button button--primary" href="#early-access">{factory.cta} <ArrowUpRight size={17} /></a></div></section>
      <section className="tester-section container" id="early-access"><div className="tester-grid"><div className="tester-copy"><span className="kicker">{tester.kicker}</span><h2>{tester.title}</h2><p>{tester.body}</p><div className="tester-proof"><span>01</span><span>FREE ACCESS</span><span>LOCAL AUDIO</span></div></div><form className="tester-form" action="https://formsubmit.co/dudichatam@gmail.com" method="POST"><input type="hidden" name="_subject" value="L Studio, New early access tester" /><input type="hidden" name="_template" value="table" /><input type="hidden" name="_captcha" value="false" /><input type="hidden" name="_next" value="https://dudichatam-max.github.io/" /><label><span>{tester.name}</span><input type="text" name="name" autoComplete="name" placeholder={tester.name} required /></label><label><span>{tester.email}</span><input type="email" name="email" autoComplete="email" placeholder={tester.email} required /></label><label className="tester-consent"><input type="checkbox" required /><span>{language === "he" ? "אני מאשר/ת לקבל עדכונים על L Studio." : language === "ru" ? "Я согласен получать обновления о L Studio." : language === "ar" ? "أوافق على تلقي تحديثات L Studio." : "I agree to receive L Studio updates."}</span></label><button className="button button--primary" type="submit">{tester.submit} <ArrowUpRight size={16} /></button><small>{tester.note}</small></form></div></section>
      <section className="hero container" aria-labelledby="hero-title"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot" /> {text.productKicker} / API 36</div><h1 id="hero-title">{text.productLead}<br /><em>{text.productAccent}</em></h1><p className="hero-lede">{text.productBody}</p><div className="hero-actions"><a className="button button--primary" href="#early-access">{text.discover} <ArrowUpRight size={17} /></a><a className="text-link" href="#architecture">{text.engine} <ChevronRight size={16} /></a></div><div className="hero-proof"><span><b>01.02</b> VERSION</span><span><b>API 24+</b> ANDROID</span><span><b>100%</b> LOCAL AUDIO</span></div></div><div className="hero-console" aria-label="L Studio console"><div className="console-topline"><span>LIVE SESSION / 01</span><span className="live-status"><i /> AUDIO ENGINE ACTIVE</span></div><div className="console-display"><div className="display-mark"><img src={`${import.meta.env.BASE_URL}assets/logo.png`} alt="L Studio" /></div><div className="display-title">L STUDIO</div><div className="display-subtitle">MICROTONAL WORKSTATION</div><div className="waveform" aria-hidden="true">{[26,42,74,48,31,57,88,42,69,36,62,93,52,33,72,45,25,60,38,79,46,30,66,40,82,55,33,70,45,27,64,39].map((height, index) => <span key={index} style={{ height: `${height}%` }} />)}</div><div className="display-reading"><span>DO</span><strong>222.00 <small>Hz</small></strong><span>OCT +01</span></div></div><div className="console-controls"><div className="control-group"><span className="control-label">WAVE</span><span className="knob knob--gold" /><b>SAW</b></div><div className="control-group"><span className="control-label">CUTOFF</span><span className="knob" /><b>68%</b></div><div className="control-group"><span className="control-label">RESONANCE</span><span className="knob knob--gold" /><b>42%</b></div><div className="control-group"><span className="control-label">DRIVE</span><span className="knob knob--gold" /><b>WARM</b></div></div><div className="console-tabs"><span className="is-active">SOUND</span><span>MIC</span><span>LOOP</span><span>PAD</span><span>DRUM</span></div><div className="console-corner">L / 01 <span>▰▰▰</span></div></div></section>
      <div className="signal-strip"><div className="container signal-inner"><span>THE SIGNAL PATH</span><b>KEYBOARD <i>←</i> DSP ENGINE <i>←</i> LIVE BUS <i>←</i> STEREO MIX</b><span>NO THIRD-PARTY SYNTH</span></div></div>
      <section className="interface-section container" id="features"><div className="section-heading"><div><span className="kicker">{text.interfaceKicker}</span><h2>{text.interfaceTitle.split(" ").slice(0, -1).join(" ")}<br /><em>{text.interfaceTitle.split(" ").slice(-1)}</em></h2></div><p>{text.interfaceText}</p></div><div className="interface-grid"><div className="interface-feature-list">{features.map((feature, index) => { const Icon = feature.icon; return <button className={`interface-feature ${activeFeature === feature.id ? "is-active" : ""}`} key={feature.id} onClick={() => setActiveFeature(feature.id)}><span className="feature-index">0{index + 1}</span><span className="feature-icon"><Icon size={20} /></span><span className="feature-label">{feature.label}</span><ChevronRight size={16} /></button>; })}</div><div className="interface-preview"><div className="preview-image-wrap"><img src={selectedFeature.image} alt={`${selectedFeature.label} interface`} /><div className="preview-overlay"><span>{selectedFeature.meta}</span><span><SelectedIcon size={17} /> {selectedFeature.label}</span></div></div><div className="preview-copy"><span className="kicker">{selectedFeature.meta}</span><h3>{selectedFeature.title}</h3><p>{selectedFeature.description}</p></div></div></div></section>
      <section className="architecture-section" id="architecture"><div className="container architecture-grid"><div className="architecture-copy"><span className="kicker">02 / UNDER THE HOOD</span><h2>{text.under}<br /><em>{text.holds}</em></h2><p>{text.underText}</p><div className="pipeline"><span>KEYBOARD</span><i>→</i><span>DSP / VOICES</span><i>→</i><span>FX / MIX</span><i>→</i><span>WAV</span></div></div><div className="architecture-art"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="architecture-core"><AudioWaveform size={42} /><span>REAL-TIME</span><b>LOCAL AUDIO</b></div></div></div></section>
      <section className="vision-section" id="vision"><div className="container vision-grid"><div className="vision-copy"><span className="kicker">{text.visionKicker}</span><h2>{text.visionTitle.split(" ").slice(0, -2).join(" ")}<br /><em>{text.visionTitle.split(" ").slice(-2).join(" ")}</em></h2><p>{text.visionBody}</p><p>{text.visionBody2}</p><a className="instagram-link" href="https://www.instagram.com/lstudio.app?stkn=MTJ2Ym1vdHBpMTA5Nw==" target="_blank" rel="noreferrer"><Instagram size={17} /> {language === "he" ? "הצטרפו לקהילה באינסטגרם" : language === "ru" ? "Присоединиться к сообществу в Instagram" : language === "ar" ? "انضم إلى المجتمع على Instagram" : "Join the community on Instagram"} <ArrowUpRight size={15} /></a></div><div className="vision-cards"><div className="vision-card"><span className="vision-card-no">01</span><Sparkles size={21} /><h3>{text.access}</h3><p>{text.accessText}</p></div><div className="vision-card"><span className="vision-card-no">02</span><Music2 size={21} /><h3>{text.community}</h3><p>{text.communityText}</p></div><div className="vision-card"><span className="vision-card-no">03</span><ArrowDownLeft size={21} /><h3>{text.future}</h3><p>{text.futureText}</p></div></div></div></section>
      <section className="final-cta container"><span className="kicker">04 / YOUR FREQUENCY</span><h2>{text.next}<br /><em>{text.waits}</em></h2><p>{text.ctaText}</p><a className="button button--primary" href="#early-access">{text.discover} <ArrowUpRight size={17} /></a></section>
    </main>
    <footer className="site-footer"><div className="container footer-inner"><SiteLogo compact /><div className="footer-links"><a href="#features">{text.features}</a><a href="#vision">{text.vision}</a><Link href="/privacy">{text.privacy}</Link></div><span className="footer-copy">© 2026 L Studio / BUILT FOR SOUND</span></div></footer>
  </div>;
}
